services:
  - type: web
    name: krb-saas-api
    env: node
    region: frankfurt
    buildCommand: cd server && npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
